"""Unit tests for scripts/template_setup/set_python_version.py.

The template_setup folder is not a package, so the module is imported by adding
the folder to sys.path, mirroring how the setup scripts import their shared
_common module (and how test_cleanup.py imports cleanup).

This file is itself a dev-script test: cleanup.py matches it to
scripts/template_setup/set_python_version.py and deletes it along with the rest
of the scaffolding, so it never lingers in a project started from the template.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts" / "template_setup"))

# mypy cannot see the sys.path insertion above, so it cannot resolve the module.
import set_python_version  # type: ignore[import-not-found]

# A representative slice of each file that declares the version, in every form.
FILES = {
    ".python-version": "3.13\n",
    "pyproject.toml": (
        'requires-python = ">=3.13"\ntarget-version = "py313"\npython_version = "3.13"\n'
    ),
    ".pre-commit-config.yaml": "default_language_version:\n  python: python3.13\n",
    "CONTRIBUTING.md": "Requires Python 3.13+ and uv.\n",
    "README.md": "[![Python](https://img.shields.io/badge/python-3.13%2B-blue)](x)\n",
    ".github/ISSUE_TEMPLATE/bug_report.yml": (
        "  - type: input\n"
        "    id: version\n"
        "    attributes:\n"
        '      placeholder: "1.0.0"\n'
        "  - type: input\n"
        "    id: python-version\n"
        "    attributes:\n"
        "      label: Python version\n"
        '      placeholder: "3.13.3"\n'
    ),
    # Generated; the script must never rewrite this one.
    "uv.lock": 'requires-python = ">=3.13"\nurl = ".../py313-none-any.whl"\n',
}


def _make_tree(root: Path) -> None:
    """Populate ``root`` with a minimal copy of the template's version files."""
    for relpath, contents in FILES.items():
        path = root / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


def test_version_forms_two_part() -> None:
    """A MAJOR.MINOR version yields matching dotted and compact forms."""
    assert set_python_version.version_forms("3.14") == ("3.14", "3.14", "py314")


def test_version_forms_three_part() -> None:
    """A MAJOR.MINOR.PATCH version keeps the patch only in the full form."""
    assert set_python_version.version_forms("3.13.3") == ("3.13.3", "3.13", "py313")


def test_version_forms_strips_whitespace() -> None:
    """Surrounding whitespace is trimmed before parsing."""
    assert set_python_version.version_forms("  3.14  ") == ("3.14", "3.14", "py314")


@pytest.mark.parametrize("bad", ["3", "abc", "", "3.", "py313"])
def test_version_forms_rejects_invalid(bad: str) -> None:
    """Anything that is not MAJOR.MINOR[.PATCH] raises ValueError."""
    with pytest.raises(ValueError, match="not a valid Python version"):
        set_python_version.version_forms(bad)


def test_run_updates_every_declared_form(tmp_path: Path) -> None:
    """Running the step rewrites all three spellings across every file."""
    _make_tree(tmp_path)
    assert set_python_version.run(tmp_path, "3.14", assume_yes=True) == 0

    assert (tmp_path / ".python-version").read_text(encoding="utf-8") == "3.14\n"
    pyproject = (tmp_path / "pyproject.toml").read_text(encoding="utf-8")
    assert '">=3.14"' in pyproject
    assert '"py314"' in pyproject
    assert 'python_version = "3.14"' in pyproject
    assert "python3.14" in (tmp_path / ".pre-commit-config.yaml").read_text(encoding="utf-8")
    assert "Python 3.14+" in (tmp_path / "CONTRIBUTING.md").read_text(encoding="utf-8")
    assert "python-3.14%2B" in (tmp_path / "README.md").read_text(encoding="utf-8")


def test_run_keeps_patch_in_issue_template(tmp_path: Path) -> None:
    """Only the placeholder's major.minor changes; the example patch is kept."""
    _make_tree(tmp_path)
    set_python_version.run(tmp_path, "3.14", assume_yes=True)

    bug_report = (tmp_path / ".github/ISSUE_TEMPLATE/bug_report.yml").read_text(encoding="utf-8")
    assert '"3.14.3"' in bug_report
    # The unrelated package-version placeholder must be left untouched.
    assert '"1.0.0"' in bug_report


def test_run_never_touches_uv_lock(tmp_path: Path) -> None:
    """uv.lock is generated and must be regenerated by uv, not text-edited."""
    _make_tree(tmp_path)
    set_python_version.run(tmp_path, "3.14", assume_yes=True)

    assert (tmp_path / "uv.lock").read_text(encoding="utf-8") == FILES["uv.lock"]


def test_run_is_idempotent(tmp_path: Path) -> None:
    """Re-running with the version already in place reports nothing to change."""
    _make_tree(tmp_path)
    set_python_version.run(tmp_path, "3.14", assume_yes=True)
    after_first = {relpath: (tmp_path / relpath).read_text(encoding="utf-8") for relpath in FILES}

    assert set_python_version.run(tmp_path, "3.14", assume_yes=True) == 0
    for relpath, contents in after_first.items():
        assert (tmp_path / relpath).read_text(encoding="utf-8") == contents


def test_dry_run_changes_nothing(tmp_path: Path) -> None:
    """A dry run reports the plan but leaves every file untouched."""
    _make_tree(tmp_path)
    assert set_python_version.run(tmp_path, "3.14", assume_yes=True, dry_run=True) == 0
    for relpath, contents in FILES.items():
        assert (tmp_path / relpath).read_text(encoding="utf-8") == contents


def test_run_rejects_invalid_version(tmp_path: Path) -> None:
    """An invalid version raises before any file is read or written."""
    _make_tree(tmp_path)
    with pytest.raises(ValueError, match="not a valid Python version"):
        set_python_version.run(tmp_path, "nope", assume_yes=True)
